sudo: required
services:
  - docker

before_install:
  - docker build -t hf1979/docker-react -f Dockerfile.dev .

script:
  #- docker run hf1979/docker-react npm run test -- --coverage
  - docker run -e CI=true hf1979/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-224725123617"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"