FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .
# Con la -f le decimos de qué archivo tiene que tirar, en este caso de Dockerfile.dev